import {
  AllExperience,
  ExperienceType,
  ProductStatus,
} from "./experience.types";
import { Technologies } from "./technologies";

const calculateMonths = (startDate: string, endDate: string): number => {
  const parseDate = (dateStr: string) => {
    // Convert "August 2021" to "2021-08-01" for safary, it's more strict
    const parsedDate = new Date(dateStr);
    if (isNaN(parsedDate.getTime())) {
      const [monthStr, yearStr] = dateStr.split(" ");
      const month = new Date(`${monthStr} 1, ${yearStr}`).getMonth();
      return new Date(parseInt(yearStr, 10), month, 1);
    }
    return parsedDate;
  };

  const start = parseDate(startDate);
  const end = parseDate(endDate);

  return (
    (end.getFullYear() - start.getFullYear()) * 12 +
    (end.getMonth() - start.getMonth()) +
    1
  );
};

const principles = [
  { technology: Technologies.SOLID },
  { technology: Technologies.TDD },
  { technology: Technologies.YAGNI },
  { technology: Technologies.KISS },
  { technology: Technologies.DRY },
  { technology: Technologies.DesignPatterns },
];

const allExperience: AllExperience = [
  {
    title: "Founder",
    company: "Offer Inspector",
    location: "Remote",
    link: "https://offer-inspector.com/",
    startDate: "May 2025",
    endDate: "December 2025",
    responsibilities: [
      "Designed the full system architecture (frontend, backend, database) and delivered a production-ready MVP.",
      "Built containerized infrastructure with zero-downtime deployments and automated DB migrations.",
      "Developed a salary/tax calculation engine for Estonian employment models.",
      "Created core product features: workspaces, draft offers, comparison flows, visualizations.",
      "Implemented a scalable PostgreSQL schema and optimized critical queries.",
      "Set up observability stack (Prometheus, Loki, Tempo, Grafana, exporters).",
      "Managed full product lifecycle: market research, roadmap, planning, releases.",
    ],
    months: calculateMonths("May 2025", "December 2025"),
    stack: [
      { technology: Technologies.NodeJs },
      { technology: Technologies.TypeScript },
      { technology: Technologies.JavaScript },
      { technology: Technologies.Promtail },
      { technology: Technologies.Prometheus },
      { technology: Technologies.NodeExporter },
      { technology: Technologies.PostgresExporter },
      { technology: Technologies.PostgreSQL },
      { technology: Technologies.Docker },
      { technology: Technologies.DockerCompose },
      { technology: Technologies.NextJs },
      { technology: Technologies.NestJs },
      { technology: Technologies.Zustand },
      { technology: Technologies.Grafana },

      { technology: Technologies.Loki },
      { technology: Technologies.Caddy },
      { technology: Technologies.Tempo },
      ...principles,
    ],
    type: ExperienceType.Commercial,
    status: ProductStatus.InProduction,
  },
  {
    title: "Senior Software Engineer",
    company: "Katana cloud inventory",
    location: "Tallinn, Estonia | Remote",
    link: "https://katanamrp.com/",
    startDate: "August 2021",
    endDate: "September 2024",
    responsibilities: [
      "Built and optimized microservices in a distributed system (~100 services) using Kafka and PostgreSQL.",
      "Delivered cross-team features including API gateway, webhooks, sales orders, and inventory planner.",
      "Improved manufacturing planning logic, significantly reducing calculation time and errors.",
      "Led and participated in technical investigations, estimations, and epic planning.",
      "Enhanced database schemas and queries to improve performance across key services.",
      "Improved CI/CD pipelines with faster tests and more reliable deployments.",
    ],
    months: calculateMonths("August 2021", "September 2024"),
    stack: [
      { technology: Technologies.NodeJs },
      { technology: Technologies.TypeScript },
      { technology: Technologies.JavaScript },
      { technology: Technologies.Webpack },
      { technology: Technologies.Kafka },
      { technology: Technologies.PostgreSQL },
      { technology: Technologies.LoopBack3 },
      { technology: Technologies.LoopBack4 },
      { technology: Technologies.Docker },
      { technology: Technologies.Microservices },
      { technology: Technologies.Debezium },
      { technology: Technologies.Datadog },
      { technology: Technologies.AWS },
      { technology: Technologies.Aptible },
      { technology: Technologies.GithubActions },
      { technology: Technologies.Kubernetes },
      { technology: Technologies.Agile },
      { technology: Technologies.Scrum },
      { technology: Technologies.Redux },
      { technology: Technologies.ReduxSaga },
      { technology: Technologies.Jest },
      { technology: Technologies.Cypress },
      { technology: Technologies.Supertest },
      { technology: Technologies.StyledComponents },
      { technology: Technologies.HTML5 },
      { technology: Technologies.SQL },
      { technology: Technologies.React },
      { technology: Technologies.Redux },
      { technology: Technologies.ReduxSaga },
      { technology: Technologies.CSS3 },
      { technology: Technologies.StyledComponents },
      { technology: Technologies.MaterialUI },
      // { technology: Technologies.Elasticsearch },
      { technology: Technologies.REST },
      { technology: Technologies.Redis },
      { technology: Technologies.Okteto },
      { technology: Technologies.Adaptability },
      { technology: Technologies.Leadership },
      { technology: Technologies.CriticalThinking },
      { technology: Technologies.TimeManagement },
      { technology: Technologies.Websockets },
      { technology: Technologies.GithubActions },
      { technology: Technologies.ShopifyAPI },
      { technology: Technologies.Heroku },
      ...principles,
    ],
    type: ExperienceType.Commercial,
    status: ProductStatus.InProduction,
  },
  {
    title: "Senior Software Engineer",
    company: "Huawei R&D Lab",
    location: "Saint-Petersburg, Russia | Remote",
    startDate: "August 2020",
    endDate: "June 2021",
    responsibilities: [
      "Front-End Development: Built the front-end of an IDE for C/C++ developers using Visual Studio Code API, Node.js, Svelte, and TypeScript.",
      "Remote Debugging & CI/CD: Implemented a remote debugging server, set up CI/CD pipelines for packaging and delivering new versions of the extension, and integrated gRPC protocol for communication.",
    ],
    stack: [
      { technology: Technologies.NodeJs },
      { technology: Technologies.TypeScript },
      { technology: Technologies.VSCodeAPI },
      { technology: Technologies.GRPC },
      { technology: Technologies.Svelte },
      { technology: Technologies.CriticalThinking },
      { technology: Technologies.TimeManagement },
      { technology: Technologies.Webpack },
      { technology: Technologies.JavaScript },
      { technology: Technologies.HTML5 },
      { technology: Technologies.CSS3 },
      { technology: Technologies.Mocha },
      { technology: Technologies.Chai },
      { technology: Technologies.Supertest },
      { technology: Technologies.Cypress },
      { technology: Technologies.Scrum },
      { technology: Technologies.Adaptability },
      { technology: Technologies.Agile },
      { technology: Technologies.CriticalThinking },
      { technology: Technologies.TimeManagement },
      { technology: Technologies.VSCodeAPI },
      ...principles,
    ],
    months: calculateMonths("August 2020", "June 2021"),
    link: "https://career.huawei.ru/rri/en/",
    type: ExperienceType.Commercial,
    status: ProductStatus.InProduction,
  },
  {
    title: "Full-stack Developer",
    company: "Diversido",
    location: "Remote",
    link: "https://www.diversido.io/",
    startDate: "May 2018",
    endDate: "August 2020",
    responsibilities: [
      "Developed user-focused front-end features using React, Redux, and TypeScript.",
      "Built scalable back-end services with Node.js, Express/Nest.js, and PostgreSQL.",
      "Collaborated with clients and product teams to refine requirements and deliver reliable solutions.",
      "Implemented CI/CD pipelines and containerized deployments using Docker and AWS.",
      // "Contributed to architecture design and technical planning across multiple projects.",
      // "Maintained code quality with unit and integration tests (Jest, Enzyme).",
    ],
    months: calculateMonths("May 2018", "August 2020"),
    stack: [
      { technology: Technologies.NestJs },
      { technology: Technologies.React },
      { technology: Technologies.Redux },
      { technology: Technologies.ReduxSaga },
      { technology: Technologies.TypeScript },
      { technology: Technologies.NodeJs },
      { technology: Technologies.Express },
      { technology: Technologies.NestJs },
      { technology: Technologies.PostgreSQL },
      { technology: Technologies.AWS },
      { technology: Technologies.Heroku },
      { technology: Technologies.Enzyme },
      { technology: Technologies.Jest },
      { technology: Technologies.GraphQL },
      { technology: Technologies.RubyOnRails },
      { technology: Technologies.Docker },
      { technology: Technologies.ApolloClient },
      { technology: Technologies.StripeAPI },
      { technology: Technologies.Ruby },
      { technology: Technologies.SQL },
      { technology: Technologies.HTML5 },
      { technology: Technologies.JavaScript },
      { technology: Technologies.CSS3 },
      { technology: Technologies.Webpack },
      { technology: Technologies.StyledComponents },
      { technology: Technologies.MaterialUI },
      { technology: Technologies.Tailwind },
      { technology: Technologies.REST },
      { technology: Technologies.Redis },
      { technology: Technologies.Mocha },
      { technology: Technologies.Chai },
      { technology: Technologies.Supertest },
      { technology: Technologies.Scrum },
      { technology: Technologies.Adaptability },
      { technology: Technologies.Agile },
      { technology: Technologies.Leadership },
      { technology: Technologies.CriticalThinking },
      { technology: Technologies.TimeManagement },
      { technology: Technologies.Websockets },
      { technology: Technologies.SocketIO },
      { technology: Technologies.RabbitMQ },
      { technology: Technologies.Typeorm },
      { technology: Technologies.Prizma },
      ...principles,
    ],
    type: ExperienceType.Commercial,
    status: ProductStatus.InProduction,
  },
  {
    link: "https://sellbery.com/",
    title: "Full-stack Developer",
    company: "Ecombix",
    location: "Saint-Petersburg, Russia",
    startDate: "July 2017",
    endDate: "April 2018",
    responsibilities: [
      "Developed and improved a TypeScript-based integration system using RabbitMQ to connect the platform with Shopify, Magento, and WooCommerce.",
    ],
    months: calculateMonths("July 2017", "April 2018"),
    stack: [
      { technology: Technologies.Angular2 },
      { technology: Technologies.TypeScript },
      { technology: Technologies.NodeJs },
      { technology: Technologies.Mocha },
      { technology: Technologies.MongoDB },
      { technology: Technologies.Protractor },
      { technology: Technologies.Mongoose },
      { technology: Technologies.RabbitMQ },
      { technology: Technologies.EtsyAPI },
      { technology: Technologies.ShopifyAPI },
      { technology: Technologies.MagentoAPI },
      { technology: Technologies.React },
      { technology: Technologies.Redux },
      { technology: Technologies.JavaScript },
      { technology: Technologies.HTML5 },
      { technology: Technologies.CSS3 },
      { technology: Technologies.Webpack },
      { technology: Technologies.MaterialUI },
      { technology: Technologies.REST },
      { technology: Technologies.Microservices },
      { technology: Technologies.Redis },
      { technology: Technologies.Chai },
      { technology: Technologies.Supertest },
      { technology: Technologies.Docker },
      { technology: Technologies.Scrum },
      { technology: Technologies.Adaptability },
      { technology: Technologies.Agile },
      { technology: Technologies.TimeManagement },
      { technology: Technologies.Websockets },
      { technology: Technologies.SocketIO },
      ...principles,
    ],
    type: ExperienceType.Commercial,
    status: ProductStatus.InProduction,
  },
  {
    type: ExperienceType.Commercial,
    title: "Early Career (Junior Roles)",
    company: ["BurningButtons", "7Bits & Avelix"],
    location: "Omsk, Russia",
    link: ["https://burningbuttons.com/", "https://7bits.it/"],
    startDate: "September 2014",
    endDate: "March 2017",
    merged: true,
    responsibilities: [
      "Built front-end and back-end features using JavaScript and Node.js.",
      "Implemented UI components and business logic under senior supervision.",
      "Maintained legacy codebases and fixed bugs across multiple small projects.",
      "Collaborated with senior developers to learn best practices and improve code quality.",
    ],
    months: calculateMonths("September 2014", "March 2017"),
    items: [
      {
        title: "Junior Back-end Developer",
        company: "BurningButtons",
        location: "Omsk, Russia",
        link: "https://burningbuttons.com/",
        startDate: "September 2016",
        endDate: "March 2017",
        responsibilities: [
          "Developed a Facebook chatbot using Node.js, Express, and PostgreSQL, and integrated Stripe API for payment processing.",
        ],
        months: calculateMonths("September 2016", "March 2017"),
        stack: [
          { technology: Technologies.NodeJs },
          { technology: Technologies.Express },
          { technology: Technologies.PostgreSQL },
          { technology: Technologies.StripeAPI },
          { technology: Technologies.Docker },
          { technology: Technologies.TypeScript },
          { technology: Technologies.JavaScript },
          { technology: Technologies.REST },
          { technology: Technologies.MongoDB },
          { technology: Technologies.Mocha },
          { technology: Technologies.Chai },
          { technology: Technologies.Scrum },
          { technology: Technologies.Agile },
          { technology: Technologies.CriticalThinking },
          { technology: Technologies.TimeManagement },
          { technology: Technologies.FHIR },
          { technology: Technologies.MongoDB },
          { technology: Technologies.Mongoose },
          { technology: Technologies.Sequelize },
        ],
        type: ExperienceType.Commercial,
        status: ProductStatus.InProduction,
      },
      {
        title: "Junior Front-End Developer",
        link: "https://7bits.it/",
        company: "7Bits and Avelix",
        location: "Omsk, Russia",
        startDate: "September 2014",
        endDate: "September 2016",
        responsibilities: [
          "Contributed to front-end development for banking and medical applications using React and Redux.",
        ],
        months: calculateMonths("September 2014", "September 2016"),
        stack: [
          { technology: Technologies.React },
          { technology: Technologies.Redux },
          { technology: Technologies.CSS3 },
          { technology: Technologies.JavaScript },
          { technology: Technologies.HTML5 },
          { technology: Technologies.Webpack },
          { technology: Technologies.Scrum },
          { technology: Technologies.REST },
          { technology: Technologies.TwitterFlight },
          { technology: Technologies.Adaptability },
          { technology: Technologies.Agile },
          { technology: Technologies.CriticalThinking },
          { technology: Technologies.TimeManagement },
          { technology: Technologies.Jquery },
          { technology: Technologies.FHIR },
        ],
        type: ExperienceType.Commercial,
        status: ProductStatus.InProduction,
      },
    ],
  },
  // PETS
  {
    company:
      "AI-powered file organization CLI that helps you tidy up messy folders effortlessly.",
    link: "https://github.com/PerminovEugene/messy-folder-reorganizer-ai",
    status: ProductStatus.InProduction,
    title: "messy-folder-reorganizer-ai",
    location: "Remote",
    startDate: "January 2024",
    endDate: "February 2025",
    responsibilities: [],
    months: 1,
    stack: [
      { technology: Technologies.Rust },
      { technology: Technologies.Ollama },
      { technology: Technologies.REST },
    ],
    type: ExperienceType.PetProject,
    visibleOnCv: true,
  },
  {
    company:
      "Chess platform focusing on custom rules and unique game modes. Using Websockets, Nest.js, MongoDB and Docker.",
    link: "https://github.com/Real-One-Chess-King/monorepo",
    status: ProductStatus.InProgress,
    title: "Real One Chess King",
    location: "Remote",
    startDate: "December 2024",
    endDate: "November 2025",
    responsibilities: [],
    months: 3,
    stack: [
      { technology: Technologies.Websockets },
      { technology: Technologies.React },
      { technology: Technologies.SocketIO },
      { technology: Technologies.Docker },
      { technology: Technologies.NodeJs },
      { technology: Technologies.TypeScript },
      { technology: Technologies.JavaScript },
      { technology: Technologies.HTML5 },
      { technology: Technologies.CSS3 },
      { technology: Technologies.Tailwind },
      { technology: Technologies.MongoDB },
      { technology: Technologies.Mongoose },
      { technology: Technologies.Mocha },
      { technology: Technologies.Chai },
      { technology: Technologies.Supertest },
      { technology: Technologies.CriticalThinking },
      { technology: Technologies.TimeManagement },
      { technology: Technologies.Websockets },
      { technology: Technologies.SocketIO },
      { technology: Technologies.NextJs },
      { technology: Technologies.GraphQL },
      { technology: Technologies.ApolloClient },
      { technology: Technologies.NestJs },
      { technology: Technologies.NextJs },
    ],
    type: ExperienceType.PetProject,
    visibleOnCv: false,
  },
  {
    company:
      "NFT marketplace based on Ethereum, Solidity, ERC721, Hardhat, Pinata and ethers.js. Custom server for Ethereum node indexing.",
    link: "https://github.com/PerminovEugene/nft-open-marketplace",
    status: ProductStatus.InProgress,
    title: "NFT Open Marketplace",
    location: "Remote",
    startDate: "August 2024",
    endDate: "November 2024",
    responsibilities: [],
    months: 3,
    stack: [
      { technology: Technologies.NextJs },
      { technology: Technologies.Websockets },
      { technology: Technologies.React },
      { technology: Technologies.SocketIO },
      { technology: Technologies.Docker },
      { technology: Technologies.NodeJs },
      { technology: Technologies.TypeScript },
      { technology: Technologies.JavaScript },
      { technology: Technologies.HTML5 },
      { technology: Technologies.CSS3 },
      { technology: Technologies.Tailwind },
      { technology: Technologies.Gin },
      { technology: Technologies.Go },
      { technology: Technologies.REST },
      { technology: Technologies.PostgreSQL },
      { technology: Technologies.Mocha },
      { technology: Technologies.Chai },
      { technology: Technologies.Supertest },
      { technology: Technologies.Ethereum },
      { technology: Technologies.EVM },
      { technology: Technologies.Hardhat },
      { technology: Technologies.CriticalThinking },
      { technology: Technologies.TimeManagement },
      { technology: Technologies.Solidity },
      { technology: Technologies.MetaMaskSDK },
      { technology: Technologies.EthersJs },
      { technology: Technologies.PostgreSQL },
      { technology: Technologies.SQL },
    ],
    type: ExperienceType.PetProject,
    visibleOnCv: true,
  },
];

export default allExperience;
