import { AllExperience } from "./experience.types";

const allExperience: AllExperience = [
  {
    title: "Senior Software Engineer",
    company: "Katana cloud inventory",
    location: "Tallinn, Estonia",
    startDate: "2021",
    endDate: "September 2024",
    responsibilities: [
      "Microservices Development & Maintenance: Designed and optimized Node.js microservices architecture, ensuring robust and scalable integrations.",
      "Cross-Team Collaboration: Coordinated with multiple internal teams to deliver end-to-end product features, including the Katana Public API service, Webhooks, and Public API Docs.",
      "Real-Time Manufacturing Resource Planning: Implemented complex communication logic using Kafka, enabling real-time, efficient data flow between services.",
      "System Investigations, Planning & Estimations: Drove technical investigations and project estimations, ensuring seamless delivery of large-scale deployments.",
    ],
    stack: [
      "Node.js",
      "TypeScript",
      "Kafka",
      "Postgresql",
      "LoopBack 3/4",
      "Docker",
      "Microservices",
      "Debezium",
    ],
  },
  {
    title: "Senior Software Engineer",
    company: "Huawei Saint-Petersburg R&D Lab",
    location: "Remote/Office",
    startDate: "August 2020",
    endDate: "June 2021",
    responsibilities: [
      "Developed internal software for Huawei.",
      "Front-end part of IDE for C/C++ developers based on Visual Studio Code",
      "Problems investigation and solving.",
      "As a member of the R&D department, I participated in the development of a VSCode Extension tailored for C++ developers. This project presented a unique set of challenges and allowed me to work with an unconventional tech stack.",
    ],
    stack: ["Node.js", "Typescript", "VSCode API"],
  },
  {
    title: "Full-stack Developer",
    company: "Diversido",
    location: "Remote",
    startDate: "May 2018",
    endDate: "August 2020",
    responsibilities: [
      "Creation user-friendly interfaces on a modern front-end stack.",
      "Creation stable, fast and scalable backend applications",
      "Close communication with clients and product owners on a few projects.",
      "Set up CI/CD.",
      "Frequently worked on multiple projects simultaneously, adapting to context changes efficiently.",
      "Participation in projects architecture decisions.",
      "Participation in projects time estimations.",
    ],
    stack: [
      "React",
      "Redux",
      "Redux Saga",
      "Typescript",
      "Node.js",
      "Express",
      "Nest.js",
      "Postgresql",
      "AWS",
      "Heroku",
      "Enzyme",
      "Jest",
      "GraphQL",
      "Ruby on Rails",
      "Docker",
      "Apollo client",
    ],
  },
  {
    title: "Full-stack Developer",
    company: "Ecombix",
    location: "Saint-Petersburg, Russia",
    startDate: "July 2017",
    endDate: "April 2018",
    responsibilities: [
      "Built front-end and back-end parts of an application that allows connecting some E-commerce platforms.",
      "Integrated application with Shopify, Magento 1, Magento 2, Etsy, WooCommerce platforms.",
      "Worked with complicated project structure based on SOA architecture.",
      "Satisfied high restrictions on server response time.",
      "Developed multiple services using native Node.js with TypeScript, ensuring efficient service communication through RabbitMQ.",
    ],
    stack: [
      "Angular 2",
      "Typescript",
      "Node.js",
      "Ecommerce platforms APIs",
      "Mocha",
      "MongoDB",
      "Protractor",
      "Mongoose",
      "RabbitMQ",
    ],
  },
  {
    title: "Back-end Developer",
    company: "BurningButtons",
    location: "Omsk, Russia",
    startDate: "September 2016",
    endDate: "March 2017",
    responsibilities: [
      "Created chat-bot for Facebook based on Node.js and Postgres",
      "Created application for integration with FHIR (standard for health care data exchange) services",
    ],
    stack: [
      "ES6",
      "Node.js",
      "Express",
      "Docker",
      "MongoDB",
      "Mongoose",
      "PostgreSQL",
      "Sequelise",
      "Facebook Api",
      "Stripe Api",
      "mocha",
      "chai",
    ],
  },
  {
    title: "Front-end Developer",
    company: "7Bits and Avelix",
    location: "Omsk, Russia",
    startDate: "September 2014",
    endDate: "September 2016",
    responsibilities: [
      "Created parts of bank and medicine front-end applications",
    ],
    stack: [
      "ES6",
      "React",
      "Redux",
      "Webpack",
      "Twitter flight",
      "HTML",
      "CSS3",
    ],
  },
];

export default allExperience;
